// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6kQUDvfwKnH5Rc1fCHjUgUWM2o70RN8U',
    appId: '1:886869485355:web:045acf5dccf40e947d476e',
    messagingSenderId: '886869485355',
    projectId: 'planner-app-820bb',
    authDomain: 'planner-app-820bb.firebaseapp.com',
    storageBucket: 'planner-app-820bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUnHH_oiDfe8oNDhZ_-tIK8_0IlAPsHfw',
    appId: '1:886869485355:android:504a56fdc9881fc27d476e',
    messagingSenderId: '886869485355',
    projectId: 'planner-app-820bb',
    storageBucket: 'planner-app-820bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEYQhAuVGcQGy34OmwCCrU4MFEWIzqmnQ',
    appId: '1:886869485355:ios:680b35e86fdbeb327d476e',
    messagingSenderId: '886869485355',
    projectId: 'planner-app-820bb',
    storageBucket: 'planner-app-820bb.appspot.com',
    iosClientId:
        '886869485355-mqo1sipbl89sjoj6qi5dn8tj5u7d3kro.apps.googleusercontent.com',
    iosBundleId: 'com.juliaczaplejewicz.plannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEYQhAuVGcQGy34OmwCCrU4MFEWIzqmnQ',
    appId: '1:886869485355:ios:680b35e86fdbeb327d476e',
    messagingSenderId: '886869485355',
    projectId: 'planner-app-820bb',
    storageBucket: 'planner-app-820bb.appspot.com',
    iosClientId:
        '886869485355-mqo1sipbl89sjoj6qi5dn8tj5u7d3kro.apps.googleusercontent.com',
    iosBundleId: 'com.juliaczaplejewicz.plannerApp',
  );
}
